runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  GMAIL_USER: "keraaigpt.plus@gmail.com"
  GMAIL_PASS: "tnev ssds hcpx evrw"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup
