runtime: nodejs20
service: default

env_variables:
  NODE_ENV: production
  PORT: 8080
  GMAIL_USER: "keraaigpt.plus@gmail.com"
  GMAIL_PASS: "tnev ssds hcpx evrw"
  
  # Configuración de Google Cloud SQL - ACTUALIZADA
  # Reemplaza estos valores con tu configuración real
  GOOGLE_CLOUD_PROJECT: "ascendant-altar-457900-v4"
  CLOUD_SQL_CONNECTION_NAME: "ascendant-altar-457900-v4:us-central1:pando-mysql"
  CLOUD_SQL_PUBLIC_IP: "34.123.243.162"
  DB_HOST: "34.123.243.162"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWORD: "Junior.28"
  DB_NAME: "pando_db"

# Configuración automática de instancias
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Recursos del servidor
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Configuración de Cloud SQL Proxy - ACTUALIZADA
beta_settings:
  cloud_sql_instances: "ascendant-altar-457900-v4:us-central1:pando-mysql"

# Manejadores de URL
handlers:
  - url: /.*
    script: auto
    secure: always

# Servicios adicionales
inbound_services:
  - warmup
