steps:
  # Instalar dependencias
  - name: 'node:20'
    entrypoint: npm
    args: ['ci', '--only=production']
    dir: '.'

  # Desplegar en App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    dir: '.'

timeout: '10m' 