# Cloud Build configuration for automatic deployment with Google Cloud SQL
# This file enables automatic deployment when code is pushed to repository

steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--production']
    dir: '.'
    
  # Step 2: Run configuration tests
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'test-config']
    dir: '.'
    env:
      - 'NODE_ENV=production'
    
  # Step 3: Setup database (only runs if needed)
  - name: 'node:20'
    entrypoint: 'node'
    args: ['setup-gcp-database.js']
    dir: '.'
    env:
      - 'NODE_ENV=production'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    
  # Step 4: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']
    dir: '.'

# Timeout for the entire build (20 minutes)
timeout: '1200s'

# Substitutions for dynamic values
substitutions:
  _SERVICE_NAME: 'default'
  _REGION: 'us-central1'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

# Build triggers can be configured in Google Cloud Console:
# https://console.cloud.google.com/cloud-build/triggers 