# Cloud Run configuration for PANDO
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pando-frontend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/cpu-throttling: "true"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: ascendant-altar-457900-v4:europe-west1:pando-mysql
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "true"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/timeout: "300"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: ascendant-altar-457900-v4-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/ascendant-altar-457900-v4/pando-frontend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "ascendant-altar-457900-v4"
        - name: CLOUD_SQL_CONNECTION_NAME
          value: "ascendant-altar-457900-v4:europe-west1:pando-mysql"
        - name: DB_NAME
          value: "pando_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        - name: GMAIL_USER
          valueFrom:
            secretKeyRef:
              name: gmail-user
              key: latest
        - name: GMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: gmail-pass
              key: latest
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secret
              key: latest
        - name: ALLOWED_ORIGINS
          value: "https://pando-frontend-483569217524.europe-west1.run.app"
        - name: CUSTOM_DOMAIN
          value: "lwpdevelopers.online"
        - name: FORCE_HTTPS
          value: "true"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
  traffic:
  - percent: 100
    latestRevision: true
